version: "1.1.1"

services:
  app:
    build: 
      context: ./sco-app-example-frontend
      dockerfile: Dockerfile.prod
    ports:
      - 4200:80
    volumes:
      - ./sco-app-example-frontend/src:/app/src
  api:
    build: 
      context: ./sco-app-example-backend
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./sco-app-example-backend/src:/app/src
    depends_on:
      - db
  db:
    image: mongo:5.0.19-focal
    attach: false
    ports:
      - 27017:27017
    volumes:
      - sco-app-example-backend:/data/db

volumes:
  sco-app-example-backend: