version: "1.1.1"

services:
  app:
    build: ./sco-app-example-frontend
    ports:
      - 80:4200
    volumes:
      - ./sco-app-example-frontend/src:/app/src
  api:
    build: ./sco-app-example-backend
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./sco-app-example-backend/src:/app/src
    depends_on:
      - db
  db:
    #image: mongo:4.4.18 // AVX error
    image: mongo:5.0.19-focal
    attach: false
    ports:
      - 27017:27017
    volumes:
      - sco-app-example-backend:/data/db

volumes:
  sco-app-example-backend: