version: "1.1.1"

services:
  app:
    build: ./sco-angular-components-base
    ports:
      - 80:4200
    volumes:
      - ./sco-angular-components-base/src:/app/src
  api:
    build: ./sco-nestjs-utilities-base
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./sco-nestjs-utilities-base/src:/app/src
    depends_on:
      - db
  db:
    image: mongo:5.0.19-focal
    attach: false
    ports:
      - 27017:27017
    volumes:
      - sco-nestjs-utilities-base:/data/db

volumes:
  sco-nestjs-utilities-base: