version: "1.1.1"

services:
  api:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./sco-web-server-backend/src:/app/src
      - ./nodeserver:/app/backend/dist/public/nodeserver
    depends_on:
      - db
  db:
    #image: mongo:4.4.18 // AVX error
    image: mongo:5.0.19-focal
    attach: false
    ports:
      - 27017:27017
    volumes:
      - sco-web-server:/data/db

volumes:
  sco-web-server: